modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
#issueTrackerURL=
#clientSideOnly=
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Preserved: Inferno"
#updateJSONURL=
#displayURL=
logoFile = "icon.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"