# Project
version=beta-1.1.1
group=sircow.preservedinferno
java_version=21

# Common
minecraft_version=1.21.8
mod_name=Preserved-Inferno
mod_author=Sir_Cow, Perpillow
mod_id=pinferno
license=LGPL-3.0-only
credits=
description=Enhances the survival aspect of Minecraft's gameplay. Core mod for the Preserved mod set.
minecraft_version_range=[1.21.8, 1.22)

neo_form_version=1.21.8-20250717.133445
# ParchmentMC
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric
fabric_version=0.131.0+1.21.8
fabric_loader_version=0.16.14
modmenu_version=15.0.0-beta.3

# NeoForge
neoforge_version=21.8.26
neoforge_loader_version_range=[8,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
