# Project
version=beta-1.6.2
group=sircow.preservedinferno
java_version=25

# Common
minecraft_version=26.2
mod_name=Preserved-Inferno
mod_author=Sir_Cow, Perpillow
mod_id=pinferno
license=LGPL-3.0-only
credits=
description=Enhances the survival aspect of Minecraft's gameplay. Core mod for the Preserved mod set.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.158.0+26.2
fabric_loader_version=0.19.3

# Mod Compat
betteradvancements_version=0.6.0.72
jade_version=26.2.11+fabric
jei_version=30.25.0.177
lootr_version=1.24.39.121
modmenu_version=20.0.1

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.configuration-cache=false
