# Project
version=beta-1.0.6
group=sircow.preservedinferno
java_version=21

# Common
minecraft_version=1.21.7
mod_name=Preserved-Inferno
mod_author=Sir_Cow, Perpillow
mod_id=pinferno
license=LGPL-3.0-only
credits=
description=Enhances the survival aspect of Minecraft's gameplay. Core mod for the Preserved mod set.
minecraft_version_range=[1.21.7, 1.22)

neo_form_version=1.21.7-20250630.141722
# ParchmentMC
parchment_minecraft=1.21.7
parchment_version=2025.07.18

# Fabric
fabric_version=0.129.0+1.21.7
fabric_loader_version=0.16.14
modmenu_version=15.0.0-beta.3

# NeoForge
neoforge_version=21.7.7-beta
neoforge_loader_version_range=[7,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
