package sircow.preservedinferno.item;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Item;
import sircow.preservedinferno.Constants;

public class ModItemIds {
    public static final ResourceKey<Item> DREAMCATCHER = create("dreamcatcher");
    public static final ResourceKey<Item> ELDER_GUARDIAN_SPINE = create("elder_guardian_spine");
    public static final ResourceKey<Item> HOLLOW_TWINE = create("hollow_twine");
    public static final ResourceKey<Item> PHANTOM_SINEW = create("phantom_sinew");
    public static final ResourceKey<Item> RAW_HIDE = create("raw_hide");
    public static final ResourceKey<Item> LEATHER_FABRIC = create("leather_fabric");
    public static final ResourceKey<Item> GILDEN_BERRIES = create("gilden_berries");
    public static final ResourceKey<Item> RESIN_SPECK = create("resin_speck");
    public static final ResourceKey<Item> ECHOING_PRISM = create("echoing_prism");
    public static final ResourceKey<Item> ECHOING_PRISM_UPGRADE_SMITHING_TEMPLATE = create("echoing_prism_upgrade_smithing_template");
    public static final ResourceKey<Item> SCULK_INFUSION = create("sculk_infusion");
    public static final ResourceKey<Item> REVERB_COMPASS = create("reverb_compass");
    public static final ResourceKey<Item> REPAIR_KIT = create("repair_kit");
    public static final ResourceKey<Item> FORGE_DUST = create("forge_dust");
    public static final ResourceKey<Item> RAW_IRON_CHUNK = create("raw_iron_chunk");
    public static final ResourceKey<Item> RAW_GOLD_CHUNK = create("raw_gold_chunk");
    public static final ResourceKey<Item> RAW_COPPER_CHUNK = create("raw_copper_chunk");
    public static final ResourceKey<Item> QUARTZITE = create("quartzite");
    public static final ResourceKey<Item> QUARTZITE_SHOVEL = create("quartzite_shovel");
    public static final ResourceKey<Item> QUARTZITE_PICKAXE = create("quartzite_pickaxe");
    public static final ResourceKey<Item> QUARTZITE_AXE = create("quartzite_axe");
    public static final ResourceKey<Item> QUARTZITE_SCYTHE = create("quartzite_hoe");
    public static final ResourceKey<Item> QUARTZITE_SWORD = create("quartzite_sword");
    public static final ResourceKey<Item> COPPER_TRIDENT = create("copper_trident");
    public static final ResourceKey<Item> COPPER_MULTITOOL = create("copper_multitool");
    public static final ResourceKey<Item> DIAMOND_MULTITOOL = create("diamond_multitool");
    public static final ResourceKey<Item> GOLDEN_MULTITOOL = create("golden_multitool");
    public static final ResourceKey<Item> IRON_MULTITOOL = create("iron_multitool");
    public static final ResourceKey<Item> NETHER_ALLOY_MULTITOOL = create("nether_alloy_multitool");
    public static final ResourceKey<Item> NETHERITE_MULTITOOL = create("netherite_multitool");
    public static final ResourceKey<Item> QUARTZITE_MULTITOOL = create("quartzite_multitool");
    public static final ResourceKey<Item> STONE_MULTITOOL = create("stone_multitool");
    public static final ResourceKey<Item> WOODEN_MULTITOOL = create("wooden_multitool");
    public static final ResourceKey<Item> BLACK_CLOTH = create("black_cloth");
    public static final ResourceKey<Item> BLUE_CLOTH = create("blue_cloth");
    public static final ResourceKey<Item> BROWN_CLOTH = create("brown_cloth");
    public static final ResourceKey<Item> CYAN_CLOTH = create("cyan_cloth");
    public static final ResourceKey<Item> GRAY_CLOTH = create("gray_cloth");
    public static final ResourceKey<Item> GREEN_CLOTH = create("green_cloth");
    public static final ResourceKey<Item> LIGHT_BLUE_CLOTH = create("light_blue_cloth");
    public static final ResourceKey<Item> LIGHT_GRAY_CLOTH = create("light_gray_cloth");
    public static final ResourceKey<Item> LIME_CLOTH = create("lime_cloth");
    public static final ResourceKey<Item> MAGENTA_CLOTH = create("magenta_cloth");
    public static final ResourceKey<Item> ORANGE_CLOTH = create("orange_cloth");
    public static final ResourceKey<Item> PINK_CLOTH = create("pink_cloth");
    public static final ResourceKey<Item> PURPLE_CLOTH = create("purple_cloth");
    public static final ResourceKey<Item> RED_CLOTH = create("red_cloth");
    public static final ResourceKey<Item> WHITE_CLOTH = create("white_cloth");
    public static final ResourceKey<Item> YELLOW_CLOTH = create("yellow_cloth");
    public static final ResourceKey<Item> COPPER_SHIELD = create("copper_shield");
    public static final ResourceKey<Item> IRON_SHIELD = create("iron_shield");
    public static final ResourceKey<Item> DIAMOND_SHIELD = create("diamond_shield");
    public static final ResourceKey<Item> NETHERITE_SHIELD = create("netherite_shield");
    public static final ResourceKey<Item> GOLDEN_SHIELD = create("golden_shield");
    public static final ResourceKey<Item> AQUATIC_FIBER = create("aquatic_fiber");
    public static final ResourceKey<Item> NETHER_ALLOY_PLATE = create("nether_alloy_plate");
    public static final ResourceKey<Item> NETHER_ALLOY_INGOT = create("nether_alloy_ingot");
    public static final ResourceKey<Item> NETHER_ALLOY_UPGRADE_SMITHING_TEMPLATE = create("nether_alloy_upgrade_smithing_template");
    public static final ResourceKey<Item> NETHER_ALLOY_SHOVEL = create("nether_alloy_shovel");
    public static final ResourceKey<Item> NETHER_ALLOY_PICKAXE = create("nether_alloy_pickaxe");
    public static final ResourceKey<Item> NETHER_ALLOY_AXE = create("nether_alloy_axe");
    public static final ResourceKey<Item> NETHER_ALLOY_SCYTHE = create("nether_alloy_hoe");
    public static final ResourceKey<Item> NETHER_ALLOY_SWORD = create("nether_alloy_sword");
    public static final ResourceKey<Item> COPPER_FISHING_HOOK = create("copper_fishing_hook");
    public static final ResourceKey<Item> IRON_FISHING_HOOK = create("iron_fishing_hook");
    public static final ResourceKey<Item> PRISMARINE_FISHING_HOOK = create("prismarine_fishing_hook");
    public static final ResourceKey<Item> GOLDEN_FISHING_HOOK = create("golden_fishing_hook");
    public static final ResourceKey<Item> DIAMOND_FISHING_HOOK = create("diamond_fishing_hook");
    public static final ResourceKey<Item> NETHERITE_FISHING_HOOK = create("netherite_fishing_hook");
    public static final ResourceKey<Item> COPPER_LACED_FISHING_LINE = create("copper_laced_fishing_line");
    public static final ResourceKey<Item> IRON_LACED_FISHING_LINE = create("iron_laced_fishing_line");
    public static final ResourceKey<Item> PRISMARINE_LACED_FISHING_LINE = create("prismarine_laced_fishing_line");
    public static final ResourceKey<Item> GOLDEN_LACED_FISHING_LINE = create("golden_laced_fishing_line");
    public static final ResourceKey<Item> DIAMOND_LACED_FISHING_LINE = create("diamond_laced_fishing_line");
    public static final ResourceKey<Item> NETHERITE_LACED_FISHING_LINE = create("netherite_laced_fishing_line");
    public static final ResourceKey<Item> COPPER_SINKER = create("copper_sinker");
    public static final ResourceKey<Item> IRON_SINKER = create("iron_sinker");
    public static final ResourceKey<Item> PRISMARINE_SINKER = create("prismarine_sinker");
    public static final ResourceKey<Item> GOLDEN_SINKER = create("golden_sinker");
    public static final ResourceKey<Item> DIAMOND_SINKER = create("diamond_sinker");
    public static final ResourceKey<Item> NETHERITE_SINKER = create("netherite_sinker");
    public static final ResourceKey<Item> MUSIC_DISC_AQUA = create("music_disc_aqua");
    public static final ResourceKey<Item> FLARE_GUN = create("flare_gun");
    public static final ResourceKey<Item> DYNAMITE = create("dynamite");
    public static final ResourceKey<Item> LAVA_BOTTLE = create("lava_bottle");
    public static final ResourceKey<Item> SPLASH_LAVA_BOTTLE = create("splash_lava_bottle");
    public static final ResourceKey<Item> LINGERING_LAVA_BOTTLE = create("lingering_lava_bottle");
    public static final ResourceKey<Item> MILK_BOTTLE = create("milk_bottle");
    public static final ResourceKey<Item> SPLASH_MILK_BOTTLE = create("splash_milk_bottle");
    public static final ResourceKey<Item> LINGERING_MILK_BOTTLE = create("lingering_milk_bottle");
    public static final ResourceKey<Item> SPLASH_HONEY_BOTTLE = create("splash_honey_bottle");
    public static final ResourceKey<Item> LINGERING_HONEY_BOTTLE = create("lingering_honey_bottle");
    public static final ResourceKey<Item> CACHE = create("cache");

    private static ResourceKey<Item> create(String name) {
        return ResourceKey.create(Registries.ITEM, Constants.id(name));
    }
}
